# Generated by Django 2.2.20 on 2021-05-04 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn', models.CharField(max_length=15)),
                ('kpp', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('houseguid', models.CharField(max_length=36)),
                ('aoguid', models.CharField(max_length=36)),
                ('house_type', models.CharField(choices=[('1', 'Жилой'), ('2', 'Жилой дом блокированной застройки'), ('3', 'Многоквартирный')], default='3', max_length=50)),
                ('housenum', models.CharField(max_length=20)),
                ('buildnum', models.CharField(max_length=10)),
                ('strucnum', models.CharField(max_length=10)),
                ('eststatus', models.CharField(choices=[('1', 'Владение'), ('2', 'Дом'), ('3', 'Домовладение'), ('4', 'Участок')], default='2', max_length=20)),
                ('strstatus', models.CharField(choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], max_length=20)),
                ('cadnum', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('management_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.organization')),
            ],
        ),
    ]
