# Generated by Django 2.2.20 on 2021-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='buildnum',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.CharField(choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='strucnum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
