# Generated by Django 2.2.20 on 2021-05-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210505_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='buildnum',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.CharField(blank=True, choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='strucnum',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
