# Generated by Django 2.2.20 on 2021-05-08 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0005_auto_20210505_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntranceNum', models.CharField(max_length=10)),
                ('StoreysCount', models.PositiveSmallIntegerField(blank=True)),
                ('CreationYear', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='LifeCycleStage',
            field=models.CharField(blank=True, choices=[('1', 'Эксплуатация'), ('2', 'Реконструкция'), ('3', 'Капитальный ремонт с отселением'), ('4', 'Капитальный ремонт без отселения')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='OlsonTZ',
            field=models.CharField(default='Москва', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='State',
            field=models.CharField(choices=[('1', 'Аварийный'), ('2', 'Исправный'), ('3', 'Ветхий')], default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='TotalSquare',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null = True),
        ),
        migrations.AddField(
            model_name='house',
            name='oktmo',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='houseguid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='ResidentialPremises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PremisesNum', models.CharField(max_length=10)),
                ('UniqueNumber', models.CharField(blank=True, max_length=10, unique=True)),
                ('PremisesCharacteristic', models.CharField(blank=True, choices=[('1', 'Отдельная квартира'), ('2', 'Квартира коммунального заселения'), ('3', 'Общежитие')], default='1', max_length=50)),
                ('TotalArea', models.DecimalField(blank=True, decimal_places=4, max_digits=25)),
                ('GrossArea', models.DecimalField(blank=True, decimal_places=4, max_digits=25)),
                ('CadastralNumber', models.CharField(blank=True, max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.Entrance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
        migrations.CreateModel(
            name='LivingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNumber', models.CharField(blank=True, max_length=10)),
                ('UniqueNumber', models.CharField(blank=True, max_length=10, unique=True)),
                ('Square', models.DecimalField(blank=True, decimal_places=4, max_digits=25)),
                ('CadastralNumber', models.CharField(blank=True, max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ResidentialPremises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.ResidentialPremises')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactoryNum', models.CharField(blank=True, max_length=20)),
                ('Type', models.CharField(blank=True, choices=[('1', 'Грузовой'), ('2', 'Пассажирский'), ('3', 'Грузопассажирский')], default='2', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Entrance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
    ]
