# Generated by Django 2.2.20 on 2021-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20210508_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
