# Generated by Django 2.2.20 on 2021-05-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20210508_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='UniqueNumber',
        ),
    ]
