# Generated by Django 2.2.20 on 2021-05-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20210508_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='author',
            field=models.ForeignKey(default='sdk2611', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='management_org',
            field=models.ForeignKey(default='ГБУ "ЖИЛИЩНИК РАЙОНА ГОЛЬЯНОВО"', on_delete=django.db.models.deletion.PROTECT, to='house.organization'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
