# Generated by Django 2.2.20 on 2021-05-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20210508_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='management_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.organization'),
        ),
    ]
