# Generated by Django 2.2.20 on 2021-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_auto_20210508_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='CulturalHeritage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='FloorCount',
            field=models.PositiveSmallIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='UndergroundFloorCount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='UsedYear',
            field=models.DateField(default='1979-01-01'),
            preserve_default=False,
        ),
    ]
