# Generated by Django 2.2.20 on 2021-05-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20210509_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='LifeCycleStage',
            field=models.CharField(blank=True, choices=[('1', 'Эксплуатация'), ('2', 'Реконструкция'), ('3', 'Капитальный ремонт с отселением'), ('4', 'Капитальный ремонт без отселения')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='State',
            field=models.CharField(choices=[('1', 'Аварийный'), ('2', 'Исправный'), ('3', 'Ветхий')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='eststatus',
            field=models.CharField(choices=[('1', 'Владение'), ('2', 'Дом'), ('3', 'Домовладение'), ('4', 'Участок')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('1', 'Жилой'), ('2', 'Жилой дом блокированной застройки'), ('3', 'Многоквартирный')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.CharField(blank=True, choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lift',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', 'Грузовой'), ('2', 'Пассажирский'), ('3', 'Грузопассажирский')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='PremisesCharacteristic',
            field=models.CharField(blank=True, choices=[('1', 'Отдельная квартира'), ('2', 'Квартира коммунального заселения'), ('3', 'Общежитие')], default='1', max_length=1),
        ),
    ]
