# Generated by Django 2.2.20 on 2021-05-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_auto_20210509_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(default=7718938741, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrance',
            name='CreationYear',
            field=models.DateField(blank=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='EntranceNum',
            field=models.CharField(max_length=10, verbose_name='Номер подъезда'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='StoreysCount',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='house',
            name='CulturalHeritage',
            field=models.BooleanField(default=False, verbose_name='Статус объекта кальтурного наследия'),
        ),
        migrations.AlterField(
            model_name='house',
            name='FloorCount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='LifeCycleStage',
            field=models.CharField(blank=True, choices=[('1', 'Эксплуатация'), ('2', 'Реконструкция'), ('3', 'Капитальный ремонт с отселением'), ('4', 'Капитальный ремонт без отселения')], default='1', max_length=1, verbose_name='Стадия жизненного цикла'),
        ),
        migrations.AlterField(
            model_name='house',
            name='OlsonTZ',
            field=models.CharField(default='Москва', max_length=50, verbose_name='Часовая зона'),
        ),
        migrations.AlterField(
            model_name='house',
            name='State',
            field=models.CharField(choices=[('1', 'Аварийный'), ('2', 'Исправный'), ('3', 'Ветхий')], default='2', max_length=1, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='house',
            name='TotalSquare',
            field=models.DecimalField(decimal_places=4, max_digits=25, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='UndergroundFloorCount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество подземных этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Идентификатор в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='UsedYear',
            field=models.DateField(verbose_name='Год ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='house',
            name='aoguid',
            field=models.CharField(max_length=36, verbose_name='Идентификатор улицы в ФИАС'),
        ),
        migrations.AlterField(
            model_name='house',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='house',
            name='buildnum',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cadnum',
            field=models.CharField(max_length=40, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='house',
            name='eststatus',
            field=models.CharField(choices=[('1', 'Владение'), ('2', 'Дом'), ('3', 'Домовладение'), ('4', 'Участок')], default='2', max_length=1, verbose_name='Признак владения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('1', 'Жилой'), ('2', 'Жилой дом блокированной застройки'), ('3', 'Многоквартирный')], default='3', max_length=1, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseguid',
            field=models.CharField(max_length=36, unique=True, verbose_name='Идентификатор в ФИАС'),
        ),
        migrations.AlterField(
            model_name='house',
            name='housenum',
            field=models.CharField(max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='management_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.organization', verbose_name='Управляющая организация'),
        ),
        migrations.AlterField(
            model_name='house',
            name='oktmo',
            field=models.CharField(max_length=11, verbose_name='Код ОКТМО'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.CharField(blank=True, choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], max_length=1, verbose_name='Признак строения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strucnum',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер строения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='Entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Entrance', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='FactoryNum',
            field=models.CharField(blank=True, max_length=20, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='Type',
            field=models.CharField(blank=True, choices=[('1', 'Грузовой'), ('2', 'Пассажирский'), ('3', 'Грузопассажирский')], default='2', max_length=1, verbose_name='Тип лифта'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='CadastralNumber',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='ResidentialPremises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.ResidentialPremises', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='RoomNumber',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='Square',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Идентификатор в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='CadastralNumber',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='Entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.Entrance', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='GrossArea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='PremisesCharacteristic',
            field=models.CharField(blank=True, choices=[('1', 'Отдельная квартира'), ('2', 'Квартира коммунального заселения'), ('3', 'Общежитие')], default='1', max_length=1, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='PremisesNum',
            field=models.CharField(max_length=10, verbose_name='Номер помещения'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='TotalArea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Идентификатор в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Дом'),
        ),
    ]
