# Generated by Django 2.2.20 on 2021-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20210509_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='CulturalHeritage',
            field=models.BooleanField(default=False, verbose_name='Статус объекта культурного наследия'),
        ),
    ]
