# Generated by Django 3.2.2 on 2021-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_auto_20210510_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='buildnum',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер корпуса'),
        ),
    ]
