# Generated by Django 3.2.2 on 2021-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_alter_house_buildnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='LifeCycleStage',
            field=models.CharField(blank=True, choices=[('1', 'Эксплуатация'), ('2', 'Реконструкция'), ('3', 'Капитальный ремонт с отселением'), ('4', 'Капитальный ремонт без отселения')], default='1', max_length=1, null=True, verbose_name='Стадия жизненного цикла'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strstatus',
            field=models.CharField(blank=True, choices=[('1', 'Строение'), ('2', 'Сооружение'), ('3', 'Литер')], max_length=1, null=True, verbose_name='Признак строения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strucnum',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер строения'),
        ),
    ]
