# Generated by Django 3.2.2 on 2021-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_auto_20210510_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='FloorCount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='TotalSquare',
            field=models.DecimalField(decimal_places=4, max_digits=25, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='UndergroundFloorCount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество подземных этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='UsedYear',
            field=models.DateField(null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
    ]
