# Generated by Django 3.2.2 on 2021-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_auto_20210510_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
    ]
