# Generated by Django 3.2.2 on 2021-05-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0023_alter_house_usedyear'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['houseguid'], name='house_house_housegu_4e2d69_idx'),
        ),
    ]
