# Generated by Django 3.2.2 on 2021-05-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0024_house_house_house_housegu_4e2d69_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrance',
            options={'ordering': ['EntranceNum']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='livingroom',
            options={'ordering': ['RoomNumber']},
        ),
        migrations.AlterModelOptions(
            name='residentialpremises',
            options={'ordering': ['PremisesNum']},
        ),
    ]
