# Generated by Django 3.2.2 on 2021-05-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0025_auto_20210518_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialpremises',
            name='CadastralNumber',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='Entrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.entrance', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='GrossArea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='TotalArea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='residentialpremises',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Идентификатор в ГИС ЖКХ'),
        ),
    ]
